namespace: retoday-global
ingress-nginx:
  namespaceOverride: ingress-nginx
  controller:
    ingressClass: nginx
    service:
      type: LoadBalancer
      annotations:
        loadbalancer.openstack.org/flavor-id: adc12270-f56a-4ef1-bb00-429aad71ef6e
        loadbalancer.openstack.org/availability-zone: KR1-Zone1-LB
      nodePorts:
        http: 30080
        https: 30443
    admissionWebhooks:
      enabled: false
cert-manager:
  namespace: cert-manager
  crds:
    enabled: true
argo-rollouts:
  namespaceOverride: argo-rollouts
  controller:
    replicas: 1
  dashboard:
    enabled: false
