namespace: retoday-global
ingress-nginx:
  namespaceOverride: ingress-nginx
  controller:
    kind: DaemonSet
    ingressClass: nginx
    config:
      use-forwarded-headers: "true"
      proxy-real-ip-cidr: 10.0.0.0/16
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      enableHttp: false
      appProtocol: false
      targetPorts:
        https: http
      annotations:
        loadbalancer.openstack.org/flavor-id: adc12270-f56a-4ef1-bb00-429aad71ef6e
        loadbalancer.openstack.org/availability-zone: KR1-Zone1-LB
        loadbalancer.openstack.org/x-forwarded-for: "true"
        loadbalancer.openstack.org/default-tls-container-ref: https://external.gabiacloud.com:9311/v1/secrets/28998961-5d7e-496f-b517-85ab7cea3bd5
      nodePorts:
        http: 30080
        https: 30443
    admissionWebhooks:
      enabled: false
cert-manager:
  namespace: cert-manager
  crds:
    enabled: true
argo-rollouts:
  namespaceOverride: argo-rollouts
  controller:
    replicas: 1
  dashboard:
    enabled: true
    readonly: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      ingressClassName: nginx
      hosts:
      - argo-rollouts.re-today.com
      tls:
      - secretName: argo-rollouts-tls
        hosts:
        - argo-rollouts.re-today.com
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
swagger:
  name: swagger
  namespace: swagger
  docsUrl: https://api.dev.re-today.com/docs/api.yaml
  ingress:
    host: swagger.re-today.com
prometheus:
  forceNamespace: prometheus
  server:
    retention: 7d
    alertmanagers:
    - static_configs:
      - targets:
        - retoday-global-alertmanager.prometheus.svc.cluster.local:9093
    extraConfigmapMounts:
    - name: alertmanager-rules
      mountPath: /etc/prometheus/alertmanager/rules
      configMap: prometheus-alertmanager-rules-cm
      readOnly: true
    persistentVolume:
      size: 15Gi
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
  prometheus-node-exporter:
    namespaceOverride: prometheus
  kube-state-metrics:
    namespaceOverride: prometheus
  alertmanager:
    namespaceOverride: prometheus
    persistence:
      enabled: false
    extraVolumeMounts:
    - name: alertmanager-templates
      mountPath: /etc/prometheus/alertmanager/templates
      readOnly: true
    extraVolumes:
    - name: alertmanager-templates
      configMap:
        name: prometheus-alertmanager-templates-cm
    extraSecretMounts:
    - name: prometheus-alertmanager-secret
      mountPath: /etc/prometheus/alertmanager/secrets
      secretName: prometheus-alertmanager-secret
      readOnly: true
    config:
      templates:
      - /etc/prometheus/alertmanager/templates/*.tmpl
      route:
        group_by:
        - alertname
        - environment
        - cronjob
        receiver: batch-receiver
        repeat_interval: 1h
      receivers:
      - name: batch-receiver
        discord_configs:
        - webhook_url_file: /etc/prometheus/alertmanager/secrets/discord-webhook-url
          send_resolved: false
          title: '{{ .CommonAnnotations.title }}'
          message: '{{ template "retoday.batch.message" . }}'
  prometheus-pushgateway:
    enabled: true
    namespaceOverride: prometheus
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
  configmapReload:
    prometheus:
      extraConfigmapMounts:
      - name: alertmanager-rules
        mountPath: /etc/prometheus/alertmanager/rules
        configMap: prometheus-alertmanager-rules-cm
        readOnly: true
      extraVolumeDirs:
      - /etc/prometheus/alertmanager/rules
  serverFiles:
    prometheus.yml:
      rule_files:
      - /etc/prometheus/alertmanager/rules/*.yaml
loki:
  namespaceOverride: loki
  deploymentMode: SingleBinary
  loki:
    limits_config:
      retention_period: 168h
    compactor:
      retention_enabled: true
      delete_request_store: filesystem
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem
    schemaConfig:
      configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  singleBinary:
    replicas: 1
    persistence:
      size: 25Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 768Mi
  read:
    replicas: 0
  write:
    replicas: 0
  backend:
    replicas: 0
  gateway:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
  memcached:
    enabled: false
  memcachedExporter:
    enabled: false
  lokiCanary:
    enabled: false
  test:
    enabled: false
  monitoring:
    dashboards:
      enabled: false
    rules:
      enabled: false
    serviceMonitor:
      enabled: false
promtail:
  namespace: promtail
  config:
    clients:
    - url: http://retoday-global-loki-gateway.loki.svc.cluster.local/loki/api/v1/push
    snippets:
      extraRelabelConfigs:
      - action: keep
        source_labels:
        - __meta_kubernetes_namespace
        regex: retoday-dev|retoday-prod|ingress-nginx
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 128Mi
grafana:
  namespaceOverride: grafana
  admin:
    existingSecret: grafana-secret
  grafana.ini:
    dashboards:
      default_home_dashboard_path: /var/lib/grafana/dashboards/retoday/api.json
  extraConfigmapMounts:
  - name: provisioning-datasources
    mountPath: /etc/grafana/provisioning/datasources
    configMap: grafana-datasources-cm
    readOnly: true
  - name: provisioning-dashboards
    mountPath: /etc/grafana/provisioning/dashboards
    configMap: grafana-dashboard-providers-cm
    readOnly: true
  dashboardsConfigMaps:
    retoday: grafana-dashboards-cm
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
    - grafana.re-today.com
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.re-today.com
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
