namespace: retoday-global
ingress-nginx:
  namespaceOverride: ingress-nginx
  controller:
    ingressClass: nginx
    service:
      type: LoadBalancer
      annotations:
        loadbalancer.openstack.org/flavor-id: adc12270-f56a-4ef1-bb00-429aad71ef6e
        loadbalancer.openstack.org/availability-zone: KR1-Zone1-LB
      nodePorts:
        http: 30080
        https: 30443
    admissionWebhooks:
      enabled: false
cert-manager:
  namespace: cert-manager
  crds:
    enabled: true
argo-cd:
  crds:
    keep: false
  namespaceOverride: argo-cd
  global:
    domain: argocd.re-today.com
  configs:
    params:
      server.insecure: true
    secret:
      createSecret: false
  dex:
    enabled: false
  server:
    replicas: 1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/ssl-redirect: true
      ingressClassName: nginx
      hostname: argocd.re-today.com
      tls: true
  notifications:
    cm:
      create: false
    secret:
      create: false
argo-rollouts:
  namespaceOverride: argo-rollouts
  controller:
    replicas: 1
  dashboard:
    enabled: false
