apiVersion: v2
name: retoday
version: 0.1.0
dependencies:
- name: mysql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.0.3
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 25.5.3
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 29.6.0
- name: grafana
  repository: https://grafana-community.github.io/helm-charts
  version: 12.3.2
