env: prod
namespace: retoday-prod
api:
  replicas: 3
  revisionHistoryLimit: 5
  image: re-today.cr.gabiacloud.com/retoday-api:3d04cdabd6b1a58474db10dc01b1cfb35218c3d1
  ingress:
    host: api.re-today.com
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      memory: 2Gi
batch:
  image: re-today.cr.gabiacloud.com/retoday-batch:3d04cdabd6b1a58474db10dc01b1cfb35218c3d1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
mysql:
  namespaceOverride: retoday-prod
  primary:
    persistence:
      size: 15Gi
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      memory: 2Gi
redis:
  namespaceOverride: retoday-prod
  master:
    persistence:
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
