env: dev
namespace: retoday-dev
ingressClassName: nginx
api:
  name: retoday-api
  replicas: 1
  revisionHistoryLimit: 1
  image: re-today.cr.gabiacloud.com/retoday-api:967370e93c3cccf1de6ae3390cac7f4ca5c7fe22
  ingress:
    host: api.dev.re-today.com
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
batch:
  name: retoday-batch
  image: re-today.cr.gabiacloud.com/retoday-batch:967370e93c3cccf1de6ae3390cac7f4ca5c7fe22
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  jobs:
    - name: generate-recap-seoul
      jobName: generateRecapJob
      schedule: "0 0 * * *"
      timeZone: Asia/Seoul
      suspend: true
      parameters:
        timeZone: SEOUL
    - name: generate-recap-pacific
      jobName: generateRecapJob
      schedule: "0 0 * * *"
      timeZone: America/Los_Angeles
      suspend: true
      parameters:
        timeZone: PACIFIC
mysql:
  namespaceOverride: retoday-dev
  fullnameOverride: retoday-mysql
  architecture: standalone
  image:
    repository: bitnamilegacy/mysql
    tag: 9.4.0-debian-12-r0
  auth:
    existingSecret: retoday-mysql-secret
    database: retoday
  primary:
    persistence:
      size: 2Gi
    service:
      ports:
        mysql: 3306
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/mysqld-exporter
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
redis:
  namespaceOverride: retoday-dev
  fullnameOverride: retoday-redis
  architecture: standalone
  auth:
    existingSecret: retoday-redis-secret
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/redis-exporter
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
cert-manager:
  issuer:
    name: letsencrypt-staging
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
