env: dev
namespace: retoday-dev
ingressClassName: nginx
api:
  name: retoday-api
  replicas: 1
  revisionHistoryLimit: 1
  image: re-today.cr.gabiacloud.com/retoday-api:ca6a49c67fa997e4cb2dc381750a6040a51f1e32
  ingress:
    host: api.dev.re-today.com
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
batch:
  name: retoday-batch
  replicas: 0
  revisionHistoryLimit: 1
  image: ""
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
mysql:
  namespaceOverride: retoday-dev
  fullnameOverride: retoday-mysql
  architecture: standalone
  image:
    repository: bitnamilegacy/mysql
    tag: 9.4.0-debian-12-r0
  auth:
    existingSecret: retoday-mysql-secret
    database: retoday
  primary:
    persistence:
      size: 2Gi
    service:
      ports:
        mysql: 3306
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
redis:
  namespaceOverride: retoday-dev
  fullnameOverride: retoday-redis
  architecture: standalone
  auth:
    existingSecret: retoday-redis-secret
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
cert-manager:
  issuer:
    name: letsencrypt-staging
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
