env: dev
namespace: retoday-dev
api:
  replicas: 1
  revisionHistoryLimit: 1
  image: re-today.cr.gabiacloud.com/retoday-api:4e262170451473034f015167c3da5e5f64173e53
  ingress:
    host: api.dev.re-today.com
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
batch:
  image: re-today.cr.gabiacloud.com/retoday-batch:4e262170451473034f015167c3da5e5f64173e53
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  jobs:
    generate-recap-seoul:
      suspend: true
    generate-recap-pacific:
      suspend: true
mysql:
  namespaceOverride: retoday-dev
  primary:
    persistence:
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
redis:
  namespaceOverride: retoday-dev
  master:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
