{{- range .Values.batch.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/component: batch
spec:
  schedule: {{ .schedule }}
  timeZone: {{ .timeZone }}
  suspend: {{ .suspend | default false }}
  concurrencyPolicy: {{ .concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit | default 3 }}
  jobTemplate:
    spec:
      backoffLimit: {{ .backoffLimit | default 1 }}
      {{- with .activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      template:
        metadata:
          labels:
            app.kubernetes.io/component: batch
        spec:
          restartPolicy: Never
          containers:
          - name: {{ .name }}
            image: {{ $.Values.batch.image }}
            imagePullPolicy: Always
            args:
            {{- range $key, $value := .parameters }}
            - {{ $key }}={{ $value }}
            {{- end }}
            - run.id=$(POD_NAME)
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $.Values.env }}
            - name: SPRING_BATCH_JOB_NAME
              value: {{ .jobName }}
            - name: BATCH_CRONJOB_NAME
              value: {{ .name }}
            - name: PROMETHEUS_PUSHGATEWAY_ADDRESS
              value: retoday-global-prometheus-pushgateway.prometheus.svc.cluster.local:9091
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            envFrom:
            - secretRef:
                name: retoday-secret
            resources:
              {{- toYaml (.resources | default $.Values.batch.resources) | nindent 14 }}
          imagePullSecrets:
          - name: docker-secret
{{- end }}
