namespace: argo-cd
argo-cd:
  crds:
    keep: true
  namespaceOverride: argo-cd
  global:
    domain: argo-cd.re-today.com
  configs:
    params:
      server.insecure: true
    secret:
      createSecret: false
  dex:
    enabled: false
  server:
    replicas: 1
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argo-cd.re-today.com
  notifications:
    cm:
      create: false
    secret:
      create: false
applications:
- name: retoday-global
  namespace: retoday-global
  path: global
  valueFiles:
  - values.yaml
- name: retoday-dev
  namespace: retoday-dev
  path: application
  valueFiles:
  - values-dev.yaml
- name: retoday-prod
  namespace: retoday-prod
  path: application
  valueFiles:
  - values-prod.yaml
